### ISSUE TITLE
whether need install efficient large-kernel convolution if use torchscript to inference?

### ISSUE THREAD

**Issue by Geek-lixiang** [VITA-Group/SLaK#6]
I first install efficient large-kernel convolution extension to train model, and then need to transfer the model to torchscript to make inference, do I need install the efficient large-kernel convolution for inference?
Thank you very much.

**Comment by Shiweiliuiiiiiii** [comment]
Hi, I am afraid that I can not give a very good answer to your question. I suggest you to as MegEngine (https://github.com/MegEngine/MegEngine/blob/master/README.md) or RepLKNet(https://github.com/DingXiaoH/RepLKNet-pytorch) for more information, since they are the one who created this efficient implementation.
